### ISSUE TITLE
can't see the button in the photo

### ISSUE THREAD

**Issue by The-Alchemist** [NeonHorizon/lipopi#12]
Great works, guys!

Unfortunately, I'm a little blind, I can't seem to find the button in the wonderful photo:

![Photo from main page](https://camo.githubusercontent.com/b5e8f81ee7a32975af369e816201ff9c3e8d69a4/68747470733a2f2f7261772e6769746875622e636f6d2f4e656f6e486f72697a6f6e2f6c69706f70692f6d61737465722f70696374757265732f6f766572766965772e6a7067)

**Comment by mindforger** [comment]
it's the one on the far right side, above the USB connector, facing to the side, wrapped in tape or shrinkwrap

a little bit hidden by the black SD card sticking out beneath

**Comment by NeonHorizon** [comment]
Yep thats the one :)
I put it there to make the whole thing as slim as possible and also have it accessible next to the USB connector on the edge.

**Comment by The-Alchemist** [comment]
Oh, it was wrapped in tape.  That's why I had trouble seeing it.

Thanks, guys!
