### ISSUE TITLE
Power up/power down version

### ISSUE THREAD

**Issue by Klonx** [NeonHorizon/lipopi#13]
Just looking for clarification on this version, the readme isn't clear as to what code is required to be installed as it talks about installing 'this' script but then doesn't show any scripts as the normal version does. Looking through the code (my python is very basic) I can't see functionality in the main version to do the power up/power down, unless I'm missing something?

**Comment by NeonHorizon** [comment]
The script hes talking about is lipopi.py which is started by lipopi.service a systemd service.
