### ISSUE TITLE
Power Up path in the Power Up / Power Down version will pull GPIO 14 above 3.3 volts

### ISSUE THREAD

**Issue by cgri** [NeonHorizon/lipopi#15]
When the push button is pressed, the power up path will pull the GPIO 14 to VBAT minus the diode forward voltage drop (through the 10 k resistor, though). On a 4.2 V lipo, this results in 3.5 V on GPIO 14 while the button is pressed.

Won't that harm the GPIO pin (on power-up until the GPIO 14 is pulled to 3.3 V internally)?

A second diode in series (as in the power down path) would prevent that.

**Comment by NeonHorizon** [comment]
It will be pretty safe through a 10k resistor as there wont be hardly any current.
