### ISSUE TITLE
Shutting straight down

### ISSUE THREAD

**Issue by urban2015** [NeonHorizon/lipopi#16]
I have followed the writing diagram and i have followed the installation of the software but my pi zero keeps shutting down when i let go of the power button. I do press and hold the button for at least 2 seconds.

I have the Pi Zero with the 500 charger board.

Any ideas ?

**Comment by NeonHorizon** [comment]
When you power it up, what voltage is on GPIO14?

**Comment by urban2015** [comment]
When i hold the power button down and measure the voltage on the that pin it is 3.4

**Comment by craic** [comment]
Have you Run sudo raspi-config and under "Advanced Options" select "Serial"
followed by No. This prevents the Pi using GPIO 14 for the console (which
would shut off the power). That step is essential (except on the Pi3!)

Also you might want to add a 0.1 uF capacitors between GPIO26 and ground

Take a look at https://github.com/craic/pi_power which I based on the
LiPoPi circuit - look for where I talk about the capacitors - I had a
couple of issues when working on a breadboard with relatively long leads,
probably due to interference. Adding the capacitor helped there.

--Rob

**Comment by urban2015** [comment]
I have run the command to disable the serial. I will look at that link you have sent as well.

**Comment by NeonHorizon** [comment]
Silly question but its worth checking, is it 3.4v on the 500 board enable pin as well.

**Comment by urban2015** [comment]
Its 3.43 on the enable pin

**Comment by NeonHorizon** [comment]
Thats odd... I guess it could have data on it which might be causing the problem.
Before we go further though is your battery OK?
What voltage is on the batt pin?

**Comment by urban2015** [comment]
There is 2.2v on the batt pin on the charger.

**Comment by urban2015** [comment]
I am just looking at the advanced options in the config and the serial option is missing. I am now running an update on it.

**Comment by craic** [comment]
2.2V ? That doesn't sound right - You are using a 3.7V LiPo battery right ?

I'm not sure how you get down to 2.2... must be completely drained

If it is not a 3.7V LiPo then it won't work

If it is, then charge it up fully and see how that works

The circuit should be working, but even a Pi Zero sucks quite a bit of
current - you might want to upgrade to PowerBoost 1000C

--Rob

**Comment by urban2015** [comment]
Here is my set up

![Uploading lipo.jpg…]()

**Comment by craic** [comment]
That jpg didn't come through - perhaps you sent the email before it had
fully uploaded - try it again

**Comment by urban2015** [comment]
Working now ?

**Comment by urban2015** [comment]
![lipo](https://cloud.githubusercontent.com/assets/14132030/22984716/28d500be-f39e-11e6-9058-db2b43fe6260.jpg)

**Comment by urban2015** [comment]
I will leave the battery on the charge for a while but without the wires in place only connecting it to from the pi to the charger with the + - the pi will run fine.

**Comment by craic** [comment]
If you have a 0.1uF capacitor, try putting it between GPIO18 and ground (I gave you the wrong pin number earlier). Your wires are pretty long and I've run into interference issues with that in other projects - worth a try...

**Comment by NeonHorizon** [comment]
2.2V on that LiPo pack is really really low. I wouldn't leave that unattended when you are charging it. Also its definitely the reason why your LiPoPi isn't working. At 2.2v you might not even be able to charge it.

**Comment by urban2015** [comment]
I will check the battery voltage without it connected to the charger 500.

**Comment by urban2015** [comment]
Its 4.0v when its not connected to the charger 500.

**Comment by urban2015** [comment]
If i plug the battery in now it comes straight on !!! werid

**Comment by urban2015** [comment]
OK i have it all connected and at the battery connecter at the back it measures 4volts

**Comment by urban2015** [comment]
I have got a 0.1 capactor when you say pin 18 and ground do you mean ground on the pi zero pin out and pin 18 on the pi zero ?

**Comment by craic** [comment]
correct - GPIO18 and Pi Ground

**Comment by urban2015** [comment]
ive added that and no didnt make a difference.

![img_0307](https://cloud.githubusercontent.com/assets/14132030/22988200/403ff67c-f3a9-11e6-9b30-e0d99ee727f5.jpg)
![img_0306](https://cloud.githubusercontent.com/assets/14132030/22988205/433a8cca-f3a9-11e6-9df3-8f5a8f336ebd.jpg)

**Comment by urban2015** [comment]
How to remove the lipopi.service? so i can try again. I am getting failed to load the lipopi.service .

I am trying the raspberian lite version os now

**Comment by urban2015** [comment]
When I install the lipopi.service script should the pi keep shutting down without the bread board connected ?

**Comment by urban2015** [comment]
Now i install the this service my pi keeps shutting down without the bread board connected

**Comment by NeonHorizon** [comment]
Yes thats correct.

**Comment by urban2015** [comment]
ok now when i connect my bread board and boot up the pi by holding the power button the pi boots up and i can see that the lipopi.service is runnning ok. I keep my finger on the power button till the login comes up and i let got of the power button and the power goes from the pi.

Can you help any more as i have now re done the bread board and measured the resistors to make sure i have 2x 10ks and 100k.

I am running rhe raspi os lite. With the serial disabled.

I would love to get this working.

**Comment by NeonHorizon** [comment]
As far as I can tell from looking at your photo its wired up correctly. As long as that breadboard doesn't have any dodgy connections. Does it stay running if you try it with the service disabled?

**Comment by urban2015** [comment]
Here is new photos.


![img_0309](https://cloud.githubusercontent.com/assets/14132030/23125928/28ebfb4e-f76c-11e6-834a-db9645335d45.JPG)
![img_0310](https://cloud.githubusercontent.com/assets/14132030/23125925/28e623a4-f76c-11e6-923a-248f625e9d90.JPG)
![img_0311](https://cloud.githubusercontent.com/assets/14132030/23125926/28e7c024-f76c-11e6-865c-ef4cd81581f3.JPG)
![img_0312](https://cloud.githubusercontent.com/assets/14132030/23125927/28ea8b56-f76c-11e6-8b2f-e2b1f362b6a2.JPG)

**Comment by urban2015** [comment]
ok i have disabled the lipopi.service and without the breadboard connected the pi stays on. With the bread board connected the pi turns off when i let go of the button.

**Comment by urban2015** [comment]
I have noticed though when i do the apt update and go to the config page the serial is no longer in the advanced section. But the serial is still disabled.

**Comment by NeonHorizon** [comment]
With the service disabled and the board disconnected you are definitely seeing 3v3 on GPIO 14 right? Because what you are describing sounds like GPIO14 is not going high on power on.

**Comment by urban2015** [comment]
OK with the bread board disconnected and running from the battery the GPio 14 is 0 all the time.

**Comment by NeonHorizon** [comment]
Something is wrong with GPIO14 then. It should go high whenever the Pi is running even when its booting.

**Comment by urban2015** [comment]
ok if i enable the serial from the config page in the inconectable options i get the 3.3 voltage back

**Comment by NeonHorizon** [comment]
You shouldn't need serial enabled but if you do use the data as the high signal you might need the capacitor mod, try it without and see.

**Comment by urban2015** [comment]
What do you mean by use the data as the high signal ?

**Comment by urban2015** [comment]
So without the script running the pi will stay on if i let go of the power button when i get the login screen. If i enable the script the pi continues to go off straight way. If i run the lipopi.py script when the service is disabled then i can shut the pi down with the power button.

**Comment by NeonHorizon** [comment]
If you turn on the serial port then there will be data on it. This can be used to simulate a high signal.

I'll let Rob get back to you about the scripts.

**Comment by urban2015** [comment]
I am wondering if the latest version of the config is different and creating problems. I will try later with the old version of the cofig and see if that changes anything. Thanks fro your help so far.

**Comment by urban2015** [comment]
OK i think i have it working :)  The config file on the serial had 2 settings first one turn off data to the serial and second one actaully turn of the serial hardware. I had turned both off duh !

OK it seams to work nicely now.

**Comment by NeonHorizon** [comment]
Oh thats really interesting!
Which settings did you use, we should clarify on the main pages.

**Comment by tommcintyre** [comment]
I can confirm - looks like there have been some changes to raspi-config menu layout. The settings are now located under "5 - Interfacing Options" / "P6 Serial". It is then necessary to answer as follows:
"Would you like a login shell to be accessible over serial?" - No
"Would you like the serial port hardware to be enabled?" - Yes

(This is on a Raspberry Pi Zero. I also added the 0.1uF capacitor between GPIO 18 and Pi Ground for good measure, although it didn't seem to be necessary. :) )

**Comment by NeonHorizon** [comment]
Thanks Tom, I've added your details to the readme and put your name in the credits.

Does anyone know if this solves the issue with the RaspberryPi 3?

Rob I'll leave you to update the pi_power documentation

**Comment by craic** [comment]
I see the changes to raspi-config... I wish they included a version number in that... 

I'll try and test this out with my circuit sometime in the next week - can't get to it sooner, unfortunately
