### ISSUE TITLE
100K resistor?

### ISSUE THREAD

**Issue by maxeph** [NeonHorizon/lipopi#19]
Hi there;
First thank you for this wonderful project. I'm very new to electronic but I know that such kind of bundle can help me in my personnal project.

It happens that I m not in possession of a 100K resistor. But I got a 1M resistor. I guess that it is ok, right?

My understanding is that the higher is that resistance the better it is!?

Thank you for confirming.

**Comment by NeonHorizon** [comment]
I dont think it will be enough to pull down the enable line but feel free to try it.
