### ISSUE TITLE
Using a 3.3v linear regulator

### ISSUE THREAD

**Issue by hex007** [NeonHorizon/lipopi#24]
I have an Adafruit 3.3v Linear regulator. Can it be used to regulate Vbat for GPIO protection? If yes haw should I modify the circuit for On and Off functionality? 

Is is ok to apply 3.3v to the output pin or regulator without connecting anything to the input?

**Comment by NeonHorizon** [comment]
No I wouldnt do that. The power consumption on on the GPIO input wouldnt be high enough for it to work properly.
