### ISSUE TITLE
UART and USB Serial

### ISSUE THREAD

**Issue by zigzaggee** [NeonHorizon/lipopi#31]
Hi I'd just like to confirm if I can still use USB serial communication on my RPi3 to my Arduino uno. I'm not quite clear if the UART TXD and RXD pins affect the USB Serial comms. Thanks in advance!

**Comment by NeonHorizon** [comment]
You should be fine LiPoPi only affects the Pi's UART, in the case of USB serial the UART will be built into the USB chip on the Arduino.
