### ISSUE TITLE
lipopi.py script query

### ISSUE THREAD

**Issue by satishgunjal** [NeonHorizon/lipopi#37]
I have tested 'A Simple Press (no hold) Power Up Version with 100uf capacitor'. Power down and power up with button press works fine.
Auto shutdown if battery is low also works fine but 'lipopi.py' script always call 'lipopi_user_shutdown' instead of 'lipopi_low_battery_shutdown'.

Using same GPIO and PowerBoost 1000.

Using raspberry pi Zero W. 1N4007 (Since 1N4001 wasn't available at the time of testing) and 100uf (50v) capacitor.

**Comment by NeonHorizon** [comment]
lipopi_user_shutdown is called when shutdown_pin voltage rises.
Do you still have shutdown_pin set as GPIO 18?
Does lipopi_user_shutdown trigger quickly or only when the battery is flat?
