### ISSUE TITLE
low battery light always on 

### ISSUE THREAD

**Issue by yosorg** [NeonHorizon/lipopi#39]
I'm trying the Simple Press (no hold) version and the power up and power down options work well. But as soon as I connect the Low Battery pin to GPIO 15 the low battery light turns on and the raspi power off after start.

 I also notice that with the raspi not attached if I connect the low battery pin to ground the low battery light also comes on, I don't know if this is the expected behavior or something is wrong in my circuit.

I'm using a Pi Zero W and a power boost 1000C, in the circuit I used 1N4007 diode and 120K resistors instead of the 100K ones.

**Comment by NeonHorizon** [comment]
Yes I think it is correct that if you ground the low battery pin the light comes on.
If you are getting it when you connect the Pi it sounds like your Pi is missconfigured and has GPIO15 set as an output instead of an input?

**Comment by yosorg** [comment]
The problem was that some how I burnt the capacitor, gpio 14 and gpio 15. I replace the capacitor and use other pins and now everthings works ok
