### ISSUE TITLE
How long does the battery last?

### ISSUE THREAD

**Issue by oskarpearson** [NeonHorizon/lipopi#4]
Hi

Thanks for this - looks useful!

Would you be able to update this with details of how long the battery lasts with different capacity batteries, based on your experience with it?

Oskar

**Comment by NeonHorizon** [comment]
Hi Oskar,
You can calculate this using the watt hours.

For example if you have a 2000mAh battery and we presume that its 3.7v on average this gives you 3.7v x 2000mAh which is 7400mWh

If we now look at the power consumption of a Raspberry Pi we can work out how many Watts it uses. I use Alex's RasPi.TV site as a reference:
http://raspi.tv/2016/raspberry-pi-zero-1-3-power-usage-with-camera

So if we pick a PiZero shooting video thats 240mA @ 5v, which is 5v x 240mA = 1200mW

So we now know our battery has 7400mWh of capacity and the Pi uses 1200mW. So 7400mWh / 1200mW = 6.16 hours.

Therefore a PiZero recording video will last 6 hours on a 2000mAh battery :)
