### ISSUE TITLE
using other pin than 14

### ISSUE THREAD

**Issue by yosorg** [NeonHorizon/lipopi#40]
Since I burn my GPIO 14 I found here https://www.raspberrypi.org/documentation/configuration/config-txt/gpio.md that you can set up other pins to start high by adding something like this but with any gpio you chose to the /boot/config.txt file
gpio=12=op,dh
And to make it low when the raspy is off you can modifying the lipopi.py  starting the ping in output mode and turning it low before shutdown, something like this
GPIO.setup(12, GPIO.OUT) 
GPIO.output(12, False)
The lipopi.py does a GPIO.cleanup() but this still let some voltage in the pin, so turning the pin to low before is needed 
For me this works fine, but only works if you power off by using the button or with the low battery signal

**Comment by NeonHorizon** [comment]
Thats worth knowing, thanks!
