### ISSUE TITLE
Hold button 3 seconds to shut down

### ISSUE THREAD

**Issue by RChadwick7** [NeonHorizon/lipopi#45]
What I'd like to do is have it so a quick push of the button doesn't do anything, but holding the button in for more than 3 seconds shuts the Pi down. I'm not very good at Python. Is there an easy way to add that function?
Thanks!

**Comment by NeonHorizon** [comment]
Python isn't my thing either but my guess is one way to do it would be to start a timer (or check the time) when the button is pushed and again when its released and check its over 3 seconds. There's a lot of Python resources out there on the Internet its probably worth having a Google.
