### ISSUE TITLE
step 13 not working. Pi powers off when releasing button

### ISSUE THREAD

**Issue by MatayMayrany** [NeonHorizon/lipopi#46]
I'm trying to configure the simple set up that powers up after a few second of holding the button but the power boost and the pi both shutoff once i release the button... 
https://imgur.com/a/k45g19E
this is my set up so far. 
help pls

**Comment by NeonHorizon** [comment]
Please make sure your battery is charged, also you are missing the 100k resistor to ground.

Also I think this is a PiZero-W is that correct?
If so you may need to do step 1 of the software first.

**Comment by MatayMayrany** [comment]
Ok I do have a resistor on the backside Of the boost. It is a pi zero W but I hadn’t done the first step in the software yet. Will try, thanks for the fast reply :)

**Comment by MatayMayrany** [comment]
it worked with the step one in the software!

**Comment by NeonHorizon** [comment]
Great news!
I'll update the instructions as a reminder.
