### ISSUE TITLE
error during run process

### ISSUE THREAD

**Issue by whynot2018** [NeonHorizon/lipopi#47]
```
# ./low_bat_shutdown.sh 
bash: ./low_bat_shutdown.sh: /bin/bash^M: bad interpreter: No such file or directory
```

solution:
```
# sed -i -e 's/\r$//' low_bat_shutdown
```

**Comment by NeonHorizon** [comment]
This happens when a file is created with a text editor which uses Windows line endings instead of Unix line endings.

If you are using Windows I recommend you use Sublime Text, or Notepad++ or one of the other code editors rather than Windows Notepad, etc.
