### ISSUE TITLE
Wiring from PowerBoost 1000c to RPi 3 B

### ISSUE THREAD

**Issue by DarumasLegs** [NeonHorizon/lipopi#48]
I have followed your instructions and diagrams as closely as I can, but I’m still not getting any power to my RPi 3 B. According to your embedded images, you do not indicate any wiring between the PowerBoost 1000C’s USB power out terminals (where the full-sized USB socket can be soldered) to the RPi 3 B’s micro USB power in ports (if needed, I intended to solder wires directly to the USB test pads on the bottom of the RPi 3 B to fit into a tighter case footprint). I noticed in the original Lipopi project there are wires going from the PowerBoost 100C USB power out to the RPi micro usb power in, but those same wires do not appear in your pictures. Do I need them? Should you update the images to show them? If I don’t need them, then how does the RPi receive 5V power?

**Comment by jsinkers** [comment]
You can either connect micro USB out from the PowerBoost board directly to the power micro USB of the Rpi, or you can use wires connecting PowerBoost 5V and GND to Rpi 5V and GND. I agree the images should show this in some way.
