### ISSUE TITLE
Why is wire to GND needed?

### ISSUE THREAD

**Issue by slavapak** [NeonHorizon/lipopi#50]
Dear Daniel,

IIUC when RPi0 shuts down, GPIO14 should go low and that should turn Powerboost off.
Then why is wire to GND still needed?

Thank you!

Kind Regards,
Slava.

**Comment by NeonHorizon** [comment]
When the Pi is off or the pins are set as inputs the GPIO's should be very high impedance (IE little to no current will flow) but as mentioned having 1k resistors inline isn't a bad idea under most situations.

With reference to pulling up and down pins the Pi has software programmable pull up and down resistors which are about 50k so its usually unnecessary to have external ones. The only odd ones out are the I2C pins which I think have internal 1.8k pullups.

**Comment by slavapak** [comment]
Reviving this thread.

I just realized that if using sliding switch instead of a button, connection to Bat might be redundant if you put switch between En and junction point for GPIO14 and Bat.

Here how I assume it would work.
When switch is closed, En is shorted to Gnd, and powerboost is turned off.
Now, when you open switch, En is not connected to Gnd anymore and RPi0 boots up.
If you close switch now, RPi0 will continue working, because GPIO14 is connected to En and is high.
After you gracefully turn RPi0 off, GPIO14 will turn low, and Powerboost will turn off as well.

Unfortunately I do not know a lot about electric circuits, and I'm afrait to burn my RPi0.
Can you please confirm that it is safe to remove  link to Bat?

Thank you!

Cheers,
Slava.

**Comment by NeonHorizon** [comment]
Can you do a circuit diagram so I can see?

**Comment by slavapak** [comment]
Sure!

Here it is:
![sliding-switch](https://user-images.githubusercontent.com/3820624/65178786-60cdad00-da0e-11e9-9f37-ead51e7b14e6.png)

**Comment by NeonHorizon** [comment]
Hey that's really clever!
You are taking advantage of the tri-state output on the GPIO (hi, low, high impedance).
I *think* it should work but I don't know for sure give it a go and let us know :)

**Comment by NeonHorizon** [comment]
By the way now I understand a bit better I think I can answer your original question.
You were asking why the ground wire is needed, I'm guessing you mean the wire with the 100k resistor rather than the actual ground? The reason that is needed is because when the Pi is powered off GPIO14 is high impedance (almost open circuit) so the 100k is used as a pulldown resistor.

**Comment by slavapak** [comment]
I see.
Thank you!
