### ISSUE TITLE
Remove transparency from diagrams

### ISSUE THREAD

**Issue by BenJuan26** [NeonHorizon/lipopi#57]
Now that GitHub has an official dark mode, some diagrams are nearly impossible to read because their backgrounds are transparent, not white. Here is what it looks like for me:

![Screenshot_20210918-125940](https://user-images.githubusercontent.com/4079548/133896594-9bf87454-4b49-4344-9461-32c0aec0cd2f.png)

Consider making the backgrounds white so that they show up as intended.

**Comment by NeonHorizon** [comment]
I use dark mode as well now.
This has been done for the images in this repository.
